name: Uppies
main: com.bitwave.Uppies.Main
description: A plugin that allows players to sit, ride, crawl, and lay down.
version: 1.2
api-version: 1.21
commands:
  sit:
    description: Take a seat
    usage: /sit
  ride:
    description: Ride an entity or player
    usage: /ride <player>
  crawl:
    description: Crawl on the ground
    usage: /crawl
  lay:
    description: Lay down on the ground
    usage: /lay
